# Generated by Django 4.1.5 on 2023-01-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('Assigned_Date', models.DateField()),
                ('Deadline_Date', models.DateField()),
                ('Status', models.CharField(max_length=100, null=True)),
                ('State', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Id', models.IntegerField()),
                ('Project_Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('Task_Id', models.IntegerField(null=True)),
                ('Tasks_Name', models.CharField(max_length=20)),
                ('Assigned_Date', models.DateField()),
                ('Deadline_Date', models.DateField()),
                ('Status', models.BooleanField(default=False)),
                ('State', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Id', models.IntegerField()),
                ('Project_Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100, null=True)),
                ('Task_Id', models.IntegerField(null=True)),
                ('Tasks_Name', models.CharField(max_length=20)),
                ('Ticket_Id', models.IntegerField(null=True)),
                ('Ticket_Series', models.CharField(max_length=20)),
                ('Assigned_Date', models.DateField()),
                ('Deadline_Date', models.DateField()),
                ('Assigned_To', models.CharField(max_length=50)),
                ('Status', models.BooleanField(default=False)),
                ('State', models.IntegerField(default=0)),
            ],
        ),
    ]
