# Generated by Django 4.1.5 on 2023-01-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Task_Id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
