# Generated by Django 4.1.5 on 2023-01-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Assigned_Date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Deadline_Date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Project_Name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Status',
        ),
    ]
