# Generated by Django 4.1.5 on 2023-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_task_assigned_date_remove_task_deadline_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Project_Name',
            new_name='Developer_Name',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Tasks_Name',
            new_name='Ticket_Name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Assigned_Date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Assigned_To',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Deadline_Date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Project_Id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Ticket_Series',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Task_Id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_Id',
            field=models.IntegerField(),
        ),
    ]
