# Generated by Django 4.1.5 on 2023-01-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_ticket_dev_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
