# Generated by Django 4.1.5 on 2023-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_project_status_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='State',
            field=models.IntegerField(default=False),
        ),
    ]
