# Generated by Django 4.1.5 on 2023-01-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pics',
        ),
    ]
